### ISSUE TITLE
wave_function

### ISSUE THREAD

**Issue by kvanasselt** [openearth/xbeach-toolbox#25]
Dispersion relation in wave_function.py are not modelled correctly

**Comment by casvbem** [comment]
@kvanasselt can you describe this issue in more detail?

e.g. 
which part of the code seems to be incorrect?
what did you try and what did you get?
what did you expect and why?
how can we solve this issue?

**Comment by kvanasselt** [comment]
I will make a pull request with the issues, but to answer your question:

I found two errors:

- When calculating the the wave celerity, the formula is written down incorrectly. It should be a / sign instead of a *
- When using the dispersion relation in the wave_celerity function, the variables are noted down inconsistently

This leads to issues when calculating the required offshore depth for the extension of the slope.
